os:
  - linux
  - osx

dist: xenial
language: cpp
compiler: clang

addons:
  apt:
    sources:
      - sourceline: ppa:beineri/opt-qt-5.14.1-xenial
    packages:
      - qt514base
      - qt514x11extras
      - qt514tools
      - libgl1-mesa-dev
      - qt514imageformats
      
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update > /dev/null
      && brew upgrade qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      && brew link qt5 --force
      ;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt*/bin/qt*-env.sh; fi

script:
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install
  - find appdir/
  - mkdir -p appdir/usr/lib/

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod a+x linuxdeployqt-continuous-x86_64.AppImage; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage; fi


  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt laigter.app; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://raw.githubusercontent.com/arl/macdeployqtfix/master/macdeployqtfix.py && chmod a+x macdeployqtfix.py; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./macdeployqtfix.py laigter.app /usr/local/Cellar/qt/*/; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then zip -r laigter.zip laigter.app; fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash upload.sh Laigter*.AppImage*; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash upload.sh laigter.zip; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
